### ISSUE TITLE
Create Links

### ISSUE THREAD

**Issue by Kuhgelfische** [Kuhgelfische/CSC_478_Linktree_Clone#2]

**Comment by jonahisadev** [comment]
This sets up grabbing links from the account, as well as displaying them in an editor on a page. Saving them is not yet supported, but is the next step I will take for this. This is probably about 70% done. We still need:

* Saving edited links
* Deleting links

We can accomplish both of these tasks with AJAX requests and implement something in the backend to actually handle these requests.
